bin/cake bake all settings
bin/cake bake all parts
bin/cake bake all statuses
bin/cake bake all sexes
bin/cake bake all bloods
bin/cake bake all member_types
bin/cake bake all members
bin/cake bake all member_histories
bin/cake bake all activities
bin/cake bake all users
bin/cake bake all matomes
